#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
~/.fehbg &
picom &
xrandr --output DP-1 --auto --output DVI-I-1 --auto --left-of DP-1

bspc monitor DP-1  -d ii iii iv v vi vii viii ix x
bspc monitor DVI-I-1  -d i

bspc config border_width         2
bspc config window_gap          20
bspc config focused_border_color "#e1874d"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
